# Series 객체
- 인덱스 + 값으로 이루어진 1차원 데이터

In [2]:
import pandas as pd

# 데이터 생성 - 리스트

In [ ]:
data = [1, 2, 3]
series = pd.Series(data)
series

0    1
1    2
2    3
dtype: int64

### index 추가

In [ ]:
data = [1, 2, 3]
series = pd.Series(data, index=['A', 'B', 'C'])
series

A    1
B    2
C    3
dtype: int64

# 데이터 생성 - 딕셔너리

In [ ]:
data_dic = {
    'A': 1,
    'B': 2,
    'C': 3
}
series_dic = pd.Series(data_dic)
series_dic

A    1
B    2
C    3
dtype: int64

# 실습

In [ ]:
kakao = pd.Series([92600, 92400, 92100, 94300, 92300])
kakao

0    92600
1    92400
2    92100
3    94300
4    92300
dtype: int64

### 인덱스를 통한 데이터 접근

In [ ]:
print(kakao[0])
print(kakao[3])
print(kakao[4])

92600
94300
92300

### 리스트와 다른점
1. 인덱싱 값 지정 가능

In [ ]:
kakao2 = pd.Series(
    [92600, 92400, 92100, 94300, 92300],
    index=['2016-02-19', '2016-02-18', '2016-02-17', '2016-02-16', '2016-02-15']
)
kakao2

2016-02-19    92600
2016-02-18    92400
2016-02-17    92100
2016-02-16    94300
2016-02-15    92300
dtype: int64

- 인덱스를 문자열로 지정했기 때문에, 데이터 접근도 해당 문자열로 접근해야됨

In [ ]:
print(kakao2['2016-02-15'])

92300

# 인덱스와 값 출력

### 인덱스 출력

In [ ]:
for date_data in kakao2.index:
    print(date_data)

2016-02-19
2016-02-18
2016-02-17
2016-02-16
2016-02-15

### 값 출력

In [ ]:
for price_data in kakao2.values:
    print(price_data)

92600
92400
92100
94300
92300

In [5]:
mine   = pd.Series([10, 20, 30], index=['naver', 'sk', 'kt'])
friend = pd.Series([10, 30, 20], index=['kt', 'naver', 'sk'])

mine + friend

kt       40
naver    40
sk       40
dtype: int64

### 인덱스가 다를 경우

In [6]:
mine   = pd.Series([10, 20, 30], index=['naver', 'sk', 'kt'])
friend = pd.Series([10, 30, 20], index=['kt', 'naver', 'sk1'])

mine + friend

kt       40.0
naver    40.0
sk        NaN
sk1       NaN
dtype: float64